"""Rewrite the README results block from eval result files, so no number in it is typed by hand.

    python scripts/update_readme_metrics.py evals/results/<run>.json [more.json ...]

Rows from several result files are pooled (e.g. a suite run plus a held-out run). Held-out scenarios
(ids HO1_, HO2_, ...) are reported separately from the development suite.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
START, END = "<!-- METRICS:START -->", "<!-- METRICS:END -->"


def block(name: str, rows: list[dict]) -> list[str]:
    if not rows:
        return [f"**{name}:** not run yet."]
    by_id: dict[str, list[dict]] = {}
    for r in rows:
        by_id.setdefault(r["id"], []).append(r)
    runs, passed = len(rows), sum(r["passed"] for r in rows)
    false_success = sum(r.get("false_success", False) for r in rows)
    blocked = [r for r in rows if r["status"] == "blocked"]
    good_blocks = sum(1 for r in blocked if r["passed"])
    cost = sum(r.get("cost_usd") or 0 for r in rows)
    all_pass = sum(1 for v in by_id.values() if all(r["passed"] for r in v))
    k = max(len(v) for v in by_id.values())
    lines = [
        f"**{name}:** {passed}/{runs} runs passed across {len(by_id)} scenarios "
        f"({all_pass}/{len(by_id)} passed on every repeat, up to {k} repeats each) · "
        f"**false successes: {false_success}** · correct escalations: {good_blocks}/{len(blocked)} · "
        f"cost per passed run ${cost / passed:.3f} · total ${cost:.2f}" if passed else
        f"**{name}:** 0/{runs} runs passed · false successes: {false_success} · total ${cost:.2f}",
        "",
        "| Scenario | Passed | Statuses | Mean steps | Mean cost |",
        "|---|---|---|---|---|",
    ]
    for sid, v in by_id.items():
        statuses = ", ".join(sorted({r["status"] for r in v}))
        mean_steps = sum(r.get("steps") or 0 for r in v) / len(v)
        mean_cost = sum(r.get("cost_usd") or 0 for r in v) / len(v)
        lines.append(f"| {sid} | {sum(r['passed'] for r in v)}/{len(v)} | {statuses} | {mean_steps:.0f} | ${mean_cost:.3f} |")
    return lines


def main(paths: list[str]) -> None:
    rows, sources = [], []
    for p in paths:
        data = json.loads(Path(p).read_text(encoding="utf-8"))
        rows += data["rows"] if isinstance(data, dict) else data
        meta = data.get("meta", {}) if isinstance(data, dict) else {}
        sources.append(f"`{Path(p).name}` ({meta.get('model', '?')}, commit {meta.get('commit', '?')})")
    dev = [r for r in rows if not re.match(r"HO\d", r["id"])]
    held = [r for r in rows if re.match(r"HO\d", r["id"])]
    text = [START, "_Generated by `scripts/update_readme_metrics.py` from " + ", ".join(sources) + "; not typed by hand._", ""]
    text += block("Development suite", dev) + [""] + block("Held-out set (frozen before any run)", held) + [END]
    readme = ROOT / "README.md"
    content = readme.read_text(encoding="utf-8")
    if START in content and END in content:
        head, rest = content.split(START, 1)
        content = head + "\n".join(text) + rest.split(END, 1)[1]
    else:
        content += "\n" + "\n".join(text) + "\n"
    readme.write_text(content, encoding="utf-8")
    print(f"README updated: {len(dev)} dev runs, {len(held)} held-out runs")


if __name__ == "__main__":
    main(sys.argv[1:] or sys.exit(__doc__))
